language: elixir
elixir: '1.6.4'

script:
  - mix docs

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: doc
  on:
    branch: master